### ISSUE TITLE
doc_host and doc_baseurl are not used properly in Heroku

### ISSUE THREAD

**Issue by daviddemeij** [fastai/nbdev#37]
I am running my documentation in an Heroku app that has an url of the form https://appname.herokuapp.com which I set as `doc_host` in the `settings.ini` file and I set the `doc_baseurl` to `/`. 

When I run it like this locally it works as expected. However, when I push this to my Heroku app, the menu links don't work anymore and point to https://module instead of to https://appname.herokuapp.com/module.

The only way I can fix this is by manually editing the baseurl in `docs/_config.yml`  to:
```
baseurl: https://appname.herokuapp.com
```

and then not running `nbdev_build_lib`. When I change the `base_url` in `settings.ini` to https://appname.herokuapp.com and do run `nbdev_build_lib` it creates other problems.

For now, it is not a big problem since I can just manually change the `docs/_config.yml` before pushing it to Heroku. But maybe there is some underlying issue that is causing this behavior.

**Comment by sgugger** [comment]
I'm not familiar with Heroku at all so I don't know how this can be made to work like jekyll. For jekyll-powered website, baseurl is added to the host url (see [here](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/)) which is why this done this way.
I'm closing this issue but if you find a setting in _config.yml we can add to make your life easier (is there an hosturl for instance?) we can add that as a new functionality.

**Comment by daviddemeij** [comment]
On Heroku it is also running Jekyll, that's why I was surprised it doesn't work the same as https://nbdev.fast.ai.

We found out that it can be fixed easily by setting the `doc_host` and `doc_base` to empty in `settings.ini`, even the cross-reference links to different modules and functions seem to work perfectly now on Heroku.

**Comment by sgugger** [comment]
Maybe you need a CNAME file like [the one](https://github.com/fastai/nbdev/blob/master/docs/CNAME) we have for nbdev?

**Comment by daviddemeij** [comment]
I have tried that, but it didn't seem to change anything.

**Comment by daviddemeij** [comment]
The only thing is that is still a bit annoying with our solution is that it is now trying to find images at https://appname.herokuapp.com/module/images/image.png instead of at https://appname.herokuapp.com/images/image.png.

**Comment by sgugger** [comment]
That is expected: since your url + baseurl is `https://appname.herokuapp.com/module/`, it looks inside `https://appname.herokuapp.com/module/images`. With the images actually being in the docs/images folder, I'm not sure why the structure is not replicated on the actual deployment server?

**Comment by daviddemeij** [comment]
I mean that it is looking for images relative to the current page so for example if I am on
https://appname.herokuapp.com/utils/ it searches the images at https://appname.herokuapp.com/utils/images/example.png
(My index page is at https://appname.herokuapp.com/)

I think this was also an issue before you implemented the `doc_host` and `doc_base`.

**Comment by daviddemeij** [comment]
Actually this is only a problem locally, on the herokuapp everything works now. (just by setting `doc_host` and `doc_base` to none)

**Comment by sgugger** [comment]
Is this on the latest master branch? This should have been fixed now, using baseurl.

**Comment by daviddemeij** [comment]
Yes, it is on the latest master branch, when I change the `doc_base` to `/` the reference links do work locally but the images still have the same problem (on Heroku it only works if I set `doc_base` and `doc_host` both to nothing).

**Comment by ZivotJeKrasny** [comment]
Hi guys!
I am having the same issue, but I did not manage to work it correctly...
The positive message is it working the same locally and on Heroku. ;)

When I set to "nothing" like:
```
doc_host = 
doc_baseurl = 
```

The issue is the same as @daviddemeij decribed in https://github.com/fastai/nbdev/issues/37#issuecomment-571696636 

It means on index page everything works correctly. Images are loaded from <INDEX_PAGE>/images/...

On subpage like <INDEX_PAGE>/subpage are images loaded from <INDEX_PAGE>/subpage/images/... which return 404. The images should be loaded from <INDEX_PAGE>/images/...


When I set to "nothing" like:
```
doc_host = 
doc_baseurl = /
```

On index page CSS styles are loaded from http://css/... and are broken. Links to subpages are pointing to http://subpage :(

I am running version `nbdev==0.2.17`.
 
Do you have any advice, please?

**Comment by ZivotJeKrasny** [comment]
I just found a solution for my problem. It is a workaround but it works ;)

I used [rack-jekyll](https://github.com/adaoraul/rack-jekyll) and [rack-rewrite](https://github.com/jtrupiano/rack-rewrite). I am redirecting all request from .*/images/... to /images/...

## Quick manual
- in settings.ini
```
doc_host = 
doc_baseurl = 
```

- create file docs/config.ru
```
require 'rack/rewrite'
use Rack::Rewrite do
  r301 %r{^/.*/images/(.*)}, '/images/$1'
end

require 'rack/jekyll'
run Rack::Jekyll.new
```

- add these lines to docs/Gemfile:
```
gem "rake"
gem "rack-rewrite"
gem "rack-jekyll"
gem "puma"
```

- For running locally `bundle exec puma` and open browser http://localhost:9292

- For deploying on Heroku create file docs/Procfile:
```
web: bundle exec puma -t 8:32 -w 3 -p $PORT
```
Maybe it will be useful for somebody in future ;)
I hope I didn't missed anything ;)
