### ISSUE TITLE
nbdev_nb2md throws error when called in a notebook

### ISSUE THREAD

**Issue by urspb** [fastai/nbdev#381]
When I tried to call `nbdev_nb2md` I got the following error, which I don't know how to handle:
![image](https://user-images.githubusercontent.com/50357297/104809836-7c0e1f80-57f0-11eb-88fb-8ccd54089ac5.png)

I'm Using nbdev 1.1.11

    ➜  nb2ltx git:(master) ✗ pip list | grep nbdev
    nbdev              1.1.11

An other issue appeared, when I tried to call `nbdev_nb2md` on the command line. If I try to use the argument  `--img_path` I get an error:

    ➜  nb2ltx git:(master) ✗ nbdev_nb2md --dest tex --img_path 'tex/images' 10_Code.ipynb
    usage: nbdev_nb2md [-h] [--dest DEST] [--use_img USE_IMG] [--replace REPLACE] path_nb
    nbdev_nb2md: error: unrecognized arguments: --img_path 10_Code.ipynb

What puzzles me is the `[--use_img USE_IMG]` in the usage section of the error message. There seems to be a connection to the error message from the notebook because `--use_img` is mentioned there also . If I execute `nbdev_nb2md  -h` on the command line there is no option `--use_img` mentioned.

    ➜  nb2ltx git:(master) ✗ nbdev_nb2md  -h
    usage: nbdev_nb2md [-h] [--dest DEST] [--img_path IMG_PATH] [--jekyll JEKYLL] fname
    
    Convert the notebook in `fname` to a markdown file
    
    positional arguments:
      fname                A notebook file name to convert
    
    optional arguments:
      -h, --help           show this help message and exit
      --dest DEST          The destination folder (default: .)
      --img_path IMG_PATH  Folder to export images to (default: )
      --jekyll JEKYLL      To use jekyll metadata for your markdown file or not (default: False)

Having read the contribution guidelines, I tried to call `import fastai.utils.collect_env; fastai.utils.collect_env.show_install(1)` but was stopped by an error message. Is `fastai.utils.collect_env` still part of the current fastai version?

**Comment by hamelsmu** [comment]
This works for me 

![image](https://user-images.githubusercontent.com/1483922/105257662-1944bd00-5b3d-11eb-9038-b4da2392f241.png)

also I tried on a seperate folder/repo and works too.  Can you try nbdev_nb2md on a simple notebook with just print('hello') in it?    

I'll close this issue since I cannot reproduce.  Make sure you upgrade to the latest nbdev.

**Comment by urspb** [comment]
@hamelsmu : Still the same problem. As you proposed, I made a new notebook with one code cell with `print('Hello World')` and the result was the same as before. As I'm not using the latest commit of nbdev but the latest published release from PyPi (1.1.12) I'm thinking that the dependencies between the versions of nbdev and nbdev-template are the reason for the behaviour I'm seeing.

![image](https://user-images.githubusercontent.com/50357297/105757285-14717600-5f4e-11eb-8916-56d2f8c86f20.png)

Is there a plan for a new release on PyPi in the next days? I'm asking this, because I'm preparing a seminar starting in March where I wanted my students to use nvdev for their semester project.

**Comment by hamelsmu** [comment]
- you can test this with the latest version?
- Also I'm still not able to reproduce your error even on wifi.  Can you share your repo and your code that someone can use to reproduce?

pip install git+https://github.com/fastai/nbdev.git

**Comment by urspb** [comment]
Hi @hamelsmu ,
as you proposed, I created a repo to reproduce the issue I am  facing. You can find it here: [urspb/nbdt_issue381](https://github.com/urspb/nbdt_issue381). In the Readme.md you can read what I did (wrong?).
My boundary conditions were:
- latest commit of `fastai/nbdev_template`
- nbdev release 1.1.12

**Comment by hamelsmu** [comment]
@urspb you should fix the issues in your notebook https://github.com/urspb/nbdt_issue381/runs/1779484852?check_suite_focus=true

**Comment by hamelsmu** [comment]
(I updated my previous comment with new information)

**Comment by urspb** [comment]
@hamelsmu: As your recommended, I ran `nbdev_nb2md` in the notebook and on the command line. The md file was produced just as expected . (See [commit 25aa6eb](https://github.com/urspb/nbdt_issue381) of the test case repo)

**Comment by urspb** [comment]
@hamelsmu : Just added some other tests, which cause `nbdev_nb2md`  throwing errors when used in the shell when using arguments. Those tests are documented in the test case repository [nbdt_issue381](https://github.com/urspb/nbdt_issue381/tree/0.0.2) dedicated to this issue.

**Comment by hamelsmu** [comment]
Dows the same happen when you use it in a shell outside the notebook, like
in a terminal?

Can you share the specific commands so we can have an easier time locating
what you added?

**Comment by urspb** [comment]
Yes, the same happens in a terminal environment:
![image](https://user-images.githubusercontent.com/50357297/106622126-90ce0f80-6573-11eb-839a-38f5e599715f.png)

**Comment by hamelsmu** [comment]
@urspb yit doesn't look like there is an argument called `--img_path` per the help docs that you see printed out on the terminal.  

Perhaps you need to run `nbdev_nb2md --dest mdFiles 30_HelloPicTwo.ipynb`

**Comment by urspb** [comment]
@hamelsmu I'm confused.  `nbdev_nb2md  -h` yields:
    
    usage: nbdev_nb2md [-h] [--dest DEST] [--img_path IMG_PATH] [--jekyll JEKYLL] fname
    
    Convert the notebook in `fname` to a markdown file
    
    positional arguments:
      fname                A notebook file name to convert
    
    optional arguments:
      -h, --help           show this help message and exit
      --dest DEST          The destination folder (default: .)
      --img_path IMG_PATH  Folder to export images to (default: )
      --jekyll JEKYLL      To use jekyll metadata for your markdown file or not (default: False)

As I tried to explain in my post on Jan 16. there is a contradiction in the help message and the error message (when e.g. `--img-path` is used.

**Comment by hamelsmu** [comment]
oh wow that is confusing!  Ok I'll reopen this issue and look into it further when I have time

**Comment by hamelsmu** [comment]
Thanks this has been fixed and tested in #424 just now.  You'll have to pip install the development version of nbdev until a release is cut

`pip install git+https://github.com/fastai/nbdev.git` or `pip install -e .` from the root of this repo.

**Comment by dogweather** [comment]
I landed here because I seem to have the same problem. Trying to use `nbdev` on the command line:

```
$ nbdev_nb2md  2-python-sequences.ipynb
usage: nbdev_nb2md [-h] [--dest DEST] [--img_path IMG_PATH] [--jekyll JEKYLL] fname
nbdev_nb2md: error: argument --img_path: invalid NoneType value: ''
```

**Comment by miklevin** [comment]
Confirming problem still exists exactly as described. I'm on nbdev-1.2.6. I get the error:

nbdev_nb2md: error: argument --img_path: invalid NoneType value: 'images'

...with or without a value being set for --img_path

**Comment by Gladiator07** [comment]
Confirming that the issue still exists. I am on macos and nbdev version is 1.2.8.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/52319020/170056538-8dd33b75-e5d8-4c88-879d-33837208b73c.png">

**Comment by sethhill28** [comment]
I can confirm that this issue still exists. I'm on Windows 11 and nbdev version 1.2.11. 
<img width="394" alt="Screenshot 2022-06-20 172026" src="https://user-images.githubusercontent.com/60534554/174688135-f8cd19f7-0da6-41e9-abf3-be324bf73ce0.png">

**Comment by alexandermoore** [comment]
I'm also running into this issue when using the commandline tool (nbdev version 1.2.11, Ubuntu 22.04):
```
nbdev_nb2md: error: argument --img_path: invalid NoneType value ''
```

I think the problematic line is `img_path:None` in https://github.com/fastai/nbdev/blob/master/nbdev/export2html.py#L657:
```python
# Cell
@call_parse
def nbdev_nb2md(
    fname:str,  # A notebook file name to convert
    dest:str='.',  # The destination folder
    img_path:None="",  # Folder to export images to
    jekyll:bool_arg=False  # To use jekyll metadata for your markdown file or not
):
    ...
```
Manually changing it to `img_path:str` resolved this issue for me.

### Temporary Workaround
I've had success with this temporary workaround for now. Save the following in a new file (ex. `nb2md.py`) and run it with `python3 nb2md.py`, it should work just like `nbdev_nb2md`:
```python
import argparse
from nbdev.export2html import _nbdev_detach, convert_md


def nbdev_nb2md(
    fname:str,  # A notebook file name to convert
    dest:str='.',  # The destination folder
    img_path="",  # Folder to export images to
    jekyll=False  # To use jekyll metadata for your markdown file or not
):
    "Convert the notebook in `fname` to a markdown file"
    _nbdev_detach(fname, dest=img_path)
    convert_md(fname, dest, jekyll=jekyll, img_path=img_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Runs nbdev_nb2md')
    parser.add_argument('fname', type=str)
    parser.add_argument('--dest', type=str, default=None)
    parser.add_argument("--img_path", type=str, default=None)
    parser.add_argument("--jekyll", action="store_true", default=None)
    args_dict = vars(parser.parse_args())
    nb2md_kwargs = {k: v for k, v in args_dict.items() if v is not None}
    nbdev_nb2md(**nb2md_kwargs)
```

### Settings.ini error?
As an aside, I also got an error about `settings.ini` not being found. Grabbing it from here (https://github.com/fastai/nbdev_template/blob/master/settings.ini) and filling in the missing `{...}` fields fixed that issue for me.
