### ISSUE TITLE
nbdev_filter breaks on ghpages deploy

### ISSUE THREAD

**Issue by IgVelasco** [fastai/nbdev#966]
After pushing on my repo I get the following error on the deploy actions:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/cli.py", line 57, in nbdev_filter
    try: filt = get_config().get('exporter', FilterDefaults)()
TypeError: 'str' object is not callable
Error: Process completed with exit code 1.
```

**Comment by IgVelasco** [comment]
Gonna try the forum first !

**Comment by seeM** [comment]
No worries @IgVelasco, the forum is the preferred place for these sorts of questions, and GitHub for tracking specific bugs or feature requests, but I can try help here :)

I think this is fixed in latest master:

https://github.com/fastai/nbdev/blob/26ab9d4a86360f1cfde775c1076b682a7ba7fdcf/nbdev/cli.py#L57

I'm curious, are you using a custom `exporter` (have you specified the `exporter` key in your settings.ini file)? If so, what are you using it for? A workaround would be to exclude that from your settings if you aren't using it.

**Comment by IgVelasco** [comment]
Yes sorry for the issue creation, I realized that once I started investigating a little more. 

I do not have an exporter key in the `settings.ini`.

The thing that I think could be the problem is that my notebook needs some user interaction for authentication, but I'm not sure if that's the problem.

I'm going to reinstall nbdev and tell you if that fixed my problem!

**Comment by IgVelasco** [comment]
Reinstalling nbdev didn't fix my problem, also when I run `nbdev_filter` on my repo locally it gets stuck

**Comment by IgVelasco** [comment]
Let me know if I can provide any more info on the matter, I think as a new user I cannot post on the forum just yet @seeM 

Thanks for the help!

**Comment by seeM** [comment]
@IgVelasco is your repo public? If you could share a link to it that would be the easiest way for me to help you out

**Comment by IgVelasco** [comment]
I'll make it public for now just let me know when I can make it private again!

[Repo](https://github.com/IgVelasco/spotify-EDA)

**Comment by seeM** [comment]
You don't seem to be using the nbdev workflows. They're trying to run `nbdev_filter` but they aren't installing `nbdev`. Here are the workflows we use: https://github.com/fastai/nbdev-template/tree/master/.github/workflows

I'm not sure why you're getting the `TypeError` though. Could you share the output of this?

```python
from nbdev.config import get_config
print(get_config())
```

You can make it private again

**Comment by IgVelasco** [comment]
The problem with using the workflows is that it runs the test, and I particularly don't want to run the test since my notebook need some interaction, do you know how I can fix or workaround it?

**Comment by IgVelasco** [comment]
Output: https://pastebin.mozilla.org/yuhZdyAL#L125

**Comment by IgVelasco** [comment]
> You don't seem to be using the nbdev workflows. Your workflow is trying to run `nbdev_filter` but it isn't installing `nbdev`. Here are the workflows we use: https://github.com/fastai/nbdev-template/tree/master/.github/workflows

I forgot that I changed the workflows to try something out let me revert it, thank you very much!

**Comment by jph00** [comment]
> The problem with using the workflows is that it runs the test, and I particularly don't want to run the test since my notebook need some interaction, do you know how I can fix or workaround it?

This shouldn't run the test:

https://github.com/fastai/nbdev-template/blob/master/.github/workflows/deploy.yaml

**Comment by jph00** [comment]
BTW you've got quite a few cells that mix imports and code. You shouldn't do that: https://nbdev.fast.ai/02_Explanations/showdoc.html

**Comment by IgVelasco** [comment]
> > The problem with using the workflows is that it runs the test, and I particularly don't want to run the test since my notebook need some interaction, do you know how I can fix or workaround it?
> 
> This shouldn't run the test:
> 
> https://github.com/fastai/nbdev-template/blob/master/.github/workflows/deploy.yaml

Yep I used to have that workflow only

In [this run](https://github.com/IgVelasco/spotify-EDA/runs/8127882727?check_suite_focus=true) you can see the error, thanks I'll check the link you share

**Comment by Jaume-JCI** [comment]
If that helps, I am facing the same issue than @IgVelasco 
I use the same deploy.yaml than the one in the nbdev repo, except for the fact that I change the branch that triggers the workflow:
https://github.com/Jaume-JCI/ds-blocks/blob/nbdev2_1/.github/workflows/deploy.yaml

**Comment by chsafouane** [comment]
I got the same issue this morning while I'm using the "defaults" workflow files. Here's the error that shows up in GitHub deploy workflow:

```
Setting up quarto (1.1.168) ...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/bin/nbdev_filter", line 8, in <module>
    sys.exit(nbdev_filter())
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nbdev/cli.py", line 57, in nbdev_filter
    try: filt = get_config().get('exporter', FilterDefaults)()
TypeError: 'str' object is not callable
Error: Process completed with exit code 1.
```

**Comment by Jaume-JCI** [comment]
I was able to sort out the issue as follows:
1. Update the deploy.yaml to the latest version in the nbdev repo. There is a small difference wrt the version I had:
```
        with: {pre: 1}
```
(not sure about the impact of this difference in solving the issue tbh)
Note: in my case, I change the name of the branch because I want to deploy GH pages in a branch different than master.

2. After updating deploy.yaml, I separated all the imports that were mixed with code. This is easy to do by following the messages printed while running the workflow. 

Hope this helps!

**Comment by chsafouane** [comment]
I'm already using the version in the template and I continue to have the same error message

**Comment by IgVelasco** [comment]
> 

Could you share your full deploy.yaml?

**Comment by Jaume-JCI** [comment]
I had a link to the file in the comment above, here it is again :-)

https://github.com/Jaume-JCI/ds-blocks/blob/nbdev2_1/.github/workflows/deploy.yaml

**Comment by IgVelasco** [comment]
Saw it after commenting, my bad!

Yes worked like a charm! Looks like there is something broken in the image

**Comment by jph00** [comment]
OK I see the problem - a recent fastcore update required an nbdev release to go with it. Fixed now - please update to the latest released nbdev and this should be resolved.
